version: '3.8'

services:

  nginx:
    build: ./docker/nginx
    container_name: nginx
    volumes:
      - ./src:/app
    ports:
      - 8080:80
    depends_on:
      - php-fpm

  php-fpm:
    build: ./docker/php-fpm
    container_name: php-fpm
    volumes:
      - ./src:/app
    depends_on:
      - db

  php-cli:
    build: ./docker/php-cli
    container_name: php-cli
    volumes:
      - ./src:/app
      - composer_data:/home/appuser/.composer/cache
    environment:
      - XDG_CONFIG_HOME=/app/storage/framework
    depends_on:
      - db

  db:
    build: ./docker/mysql
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - 3308:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: azcloud
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: azcloud
      SERVICE_NAME: mysql
      TZ: Asia/Baku
    command: --sql_mode=""

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - 127.0.0.1:6379:6379

  redis-commander:
    image: rediscommander/redis-commander
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=redis
    ports:
      - 8081:8081
    depends_on:
      - redis

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8020:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - UPLOAD_LIMIT=1G
    depends_on:
      - db

volumes:
  mysql_data:
  composer_data:
  redis_data: