version: '3.8'

volumes:
  mysql_data:
  redis_data:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./src:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php-fpm

  php-fpm:
    build: ./docker/php-fpm
    container_name: php-fpm
    volumes:
      - ./src:/app
    depends_on:
      - db

  php-cli:
    build: ./docker/php-cli
    container_name: php-cli
    volumes:
      - ./src:/app
    environment:
      - XDG_CONFIG_HOME=/var/www/html/storage/framework

  db:
    build: ./docker/mysql
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - 3308:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: azcloud
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: azcloud
      SERVICE_NAME: mysql
      TZ: Asia/Baku

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - 127.0.0.1:6379:6379

  npm:
    image: node:12.16.3
    container_name: npm
    entrypoint: [ "npm" ]
    volumes:
      - ./src:/app

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8020:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - UPLOAD_LIMIT=1G
    depends_on:
      - db